### ISSUE TITLE
VCRuntime.dll

### ISSUE THREAD

**Issue by DougFL** [rnd-ash/ultimate-nag52-config-app#6]
I keep receiving this error and am not a computer person, can someone help me please?

**Comment by rnd-ash** [comment]
What operating system are you running? You may need to install the C++ redistribution package from Microsoft (if you can give me the exact name of the missing DLL it's complaining about, I can point you to the right package to install)

**Comment by DougFL** [comment]
Hi there,Thank you for responding. VCRUNTIME140.dllI have uninstalled and reinstalled the suggested program a couple times, but no success. I found that I still have VCRUNTIME140.dll still installed, I am trying to remove it now, so it can reinstall with the whole C++ package. Sorry, I am new to windows systems. DougOn Aug 12, 2023, at 6:14 AM, Ashcon Mohseninia (RAND_ASH) ***@***.***> wrote:﻿
What operating system are you running? You may need to install the C++ redistribution package from Microsoft (if you can give me the exact name of the missing DLL it's complaining about, I can point you to the right package to install)

**Comment by DougFL** [comment]
Sorry, I didn't realize that I forgot to say what windows version... 10
I uninstalled Visual Studio and jumped through all the hoops, that didn't work. I tried Re-registering VCRUNTIME140.dll and that didn't work. I ran System File Checker and that didn't work.VCRUNTIME140 is in the SYSTEM32 folder, but I cannot delete it, so I downloaded a new one and copied/pasted it over it and that didn't work. I reinstalled Visual Studio and that didn't work either. UGH! I am thinking that I want to uninstall Visual Studio, and delete the VCRUNTIME140.dll file (which fights me, saying that I am not the Administrator, which I am), then re-install Visual Studio and see if it puts a new VCRUNTIME140 into the correct place.This is exhausting!  I get it when I try running "config_app_windows.exe"
My BG Calibrator for the DSL1 is working fine. Being a software engineer, do you have any other tricks to get config_app_windows to work?  I will give you remote access!  
Please help me.  
Doug    On Saturday, August 12, 2023 at 05:02:34 PM EDT, Doug F ***@***.***> wrote:  
 
 Hi there,
Thank you for responding. VCRUNTIME140.dll
I have uninstalled and reinstalled the suggested program a couple times, but no success. I found that I still have VCRUNTIME140.dll still installed, I am trying to remove it now, so it can reinstall with the whole C++ package. Sorry, I am new to windows systems. 
Doug

On Aug 12, 2023, at 6:14 AM, Ashcon Mohseninia (RAND_ASH) ***@***.***> wrote:



﻿


What operating system are you running? You may need to install the C++ redistribution package from Microsoft (if you can give me the exact name of the missing DLL it's complaining about, I can point you to the right package to install)

**Comment by rnd-ash** [comment]
You may need the x86 version and not the x64 version of that dll. See if it exists in Windows/SysWOW64 folder

**Comment by DougFL** [comment]
Thank you… I did find one there and deleted it (thinking that was a corrupt one too), I restarted and reinstalled Visual C++ 2015-2022 Redistributable X64. Restarted… Didn’t work. On Aug 13, 2023, at 3:54 PM, Ashcon Mohseninia (RAND_ASH) ***@***.***> wrote:﻿
You may need the x86 version and not the x64 version of that dll. See if it exists in Windows/SysWOW64 folder

**Comment by DougFL** [comment]
I just returned home and see that it’s not in there. Would that be the whole Visual Studio in X86, or just another VCRUNTIME. dll in X86 version? On Aug 13, 2023, at 3:54 PM, Ashcon Mohseninia (RAND_ASH) ***@***.***> wrote:﻿
You may need the x86 version and not the x64 version of that dll. See if it exists in Windows/SysWOW64 folder

**Comment by DougFL** [comment]
WOOO HOOO!!! Thank you so much! That worked! Thank you Thank you! On Aug 13, 2023, at 3:54 PM, Ashcon Mohseninia (RAND_ASH) ***@***.***> wrote:﻿
You may need the x86 version and not the x64 version of that dll. See if it exists in Windows/SysWOW64 folder

**Comment by DougFL** [comment]
Ok, I am all in now and have a question that I haven’t seen answered. The “wheel circumference”, is that a default number, or do I input the actual circumference of the tire I am using? The 2850mm converts to a 35” diameter tire, correct? On Aug 13, 2023, at 3:54 PM, Ashcon Mohseninia (RAND_ASH) ***@***.***> wrote:﻿
You may need the x86 version and not the x64 version of that dll. See if it exists in Windows/SysWOW64 folder

**Comment by rnd-ash** [comment]
youll need to enter whatever your car has. Use the REAR wheel circumference. This is all described on the wiki

**Comment by DougFL** [comment]
I did it based on the tires that I am using… On the wiki I saw 1875(?)mm listed for my 210.025, but my tire dia is 25.3” which equates to 2018mm circumference. Thank you for your help and I look forward to getting it installed. On Aug 15, 2023, at 6:00 AM, Ashcon Mohseninia (RAND_ASH) ***@***.***> wrote:﻿
youll need to enter whatever your car has. Use the REAR wheel circumference. This is all described on the wiki
